"""aml modules: screening, risk assessments, kyb, eidv, mlro

Revision ID: 42e933246c14
Revises: 544067eefddd
Create Date: 2026-07-06 22:28:05.966537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e933246c14'
down_revision: Union[str, None] = '544067eefddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('date_generated', sa.Date(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_datasets_id'), 'sanctions_datasets', ['id'], unique=False)
    op.create_table('firm_risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='firmrastatus'), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('sectoral_ra_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('sectoral_ra_date', sa.Date(), nullable=True),
    sa.Column('nra_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('nra_date', sa.Date(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_due', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_risk_assessments_id'), 'firm_risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_firm_risk_assessments_status'), 'firm_risk_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_firm_risk_assessments_version'), 'firm_risk_assessments', ['version'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='policystatus'), nullable=False),
    sa.Column('content_note', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_id'), 'policy_documents', ['id'], unique=False)
    op.create_index(op.f('ix_policy_documents_title'), 'policy_documents', ['title'], unique=False)
    op.create_table('sanctions_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('primary_name', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('nationalities', sa.JSON(), nullable=True),
    sa.Column('regimes', sa.JSON(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['sanctions_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_entries_dataset_id'), 'sanctions_entries', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_sanctions_entries_entity_type'), 'sanctions_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sanctions_entries_external_id'), 'sanctions_entries', ['external_id'], unique=False)
    op.create_index(op.f('ix_sanctions_entries_id'), 'sanctions_entries', ['id'], unique=False)
    op.create_index(op.f('ix_sanctions_entries_primary_name'), 'sanctions_entries', ['primary_name'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_id'), 'training_records', ['id'], unique=False)
    op.create_index(op.f('ix_training_records_user_id'), 'training_records', ['user_id'], unique=False)
    op.create_table('client_matter_risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.Enum('CLIENT', 'MATTER', name='cmratype'), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('reg28_considerations', sa.JSON(), nullable=False),
    sa.Column('context_flags', sa.JSON(), nullable=False),
    sa.Column('overall_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('edd_required', sa.Boolean(), nullable=False),
    sa.Column('edd_triggers', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', 'SUPERSEDED', name='cmrastatus'), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_due', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_matter_risk_assessments_id'), 'client_matter_risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_client_matter_risk_assessments_matter_id'), 'client_matter_risk_assessments', ['matter_id'], unique=False)
    op.create_index(op.f('ix_client_matter_risk_assessments_status'), 'client_matter_risk_assessments', ['status'], unique=False)
    op.create_index('ix_cmra_matter_type_status', 'client_matter_risk_assessments', ['matter_id', 'assessment_type', 'status'], unique=False)
    op.create_table('eidv_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_dob', sa.String(length=10), nullable=True),
    sa.Column('subject_email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('diatf_certified', sa.Boolean(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eidv_checks_id'), 'eidv_checks', ['id'], unique=False)
    op.create_index(op.f('ix_eidv_checks_matter_id'), 'eidv_checks', ['matter_id'], unique=False)
    op.create_index(op.f('ix_eidv_checks_provider_ref'), 'eidv_checks', ['provider_ref'], unique=False)
    op.create_table('internal_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('subject_summary', sa.Text(), nullable=True),
    sa.Column('suspicion_details', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'UNDER_REVIEW', 'SAR_FILED', 'NO_SAR_DECISION', name='internalreportstatus'), nullable=False),
    sa.Column('mlro_notes', sa.Text(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privilege_considered', sa.Boolean(), nullable=False),
    sa.Column('privilege_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_reports_id'), 'internal_reports', ['id'], unique=False)
    op.create_index(op.f('ix_internal_reports_matter_id'), 'internal_reports', ['matter_id'], unique=False)
    op.create_index(op.f('ix_internal_reports_reporter_id'), 'internal_reports', ['reporter_id'], unique=False)
    op.create_table('kyb_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('company_number', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('officers', sa.JSON(), nullable=True),
    sa.Column('pscs', sa.JSON(), nullable=True),
    sa.Column('ownership_notes', sa.Text(), nullable=True),
    sa.Column('psc_discrepancy', sa.Text(), nullable=True),
    sa.Column('psc_discrepancy_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('psc_discrepancy_reported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['psc_discrepancy_reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyb_checks_company_number'), 'kyb_checks', ['company_number'], unique=False)
    op.create_index(op.f('ix_kyb_checks_id'), 'kyb_checks', ['id'], unique=False)
    op.create_index(op.f('ix_kyb_checks_matter_id'), 'kyb_checks', ['matter_id'], unique=False)
    op.create_table('screening_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('CLIENT', 'BENEFICIAL_OWNER', 'COUNTERPARTY', 'GIFTOR', name='screeningsubjecttype'), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CLEAR', 'POTENTIAL_MATCH', 'CONFIRMED_MATCH', 'FALSE_POSITIVE', name='screeningcheckstatus'), nullable=False),
    sa.Column('requires_escalation', sa.Boolean(), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('providers_used', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_checks_id'), 'screening_checks', ['id'], unique=False)
    op.create_index(op.f('ix_screening_checks_matter_id'), 'screening_checks', ['matter_id'], unique=False)
    op.create_table('sar_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_report_id', sa.Integer(), nullable=False),
    sa.Column('sar_reference', sa.String(length=100), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_by_id', sa.Integer(), nullable=True),
    sa.Column('daml_requested', sa.Boolean(), nullable=False),
    sa.Column('daml_filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daml_status', sa.Enum('NONE', 'AWAITING_CONSENT', 'CONSENT_GRANTED', 'CONSENT_REFUSED_MORATORIUM', 'MORATORIUM_EXPIRED', name='damlstatus'), nullable=False),
    sa.Column('consent_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moratorium_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['internal_report_id'], ['internal_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sar_records_id'), 'sar_records', ['id'], unique=False)
    op.create_index(op.f('ix_sar_records_internal_report_id'), 'sar_records', ['internal_report_id'], unique=False)
    op.create_table('screening_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('matched_name', sa.String(length=500), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('adjudication_status', sa.Enum('PENDING', 'TRUE_MATCH', 'FALSE_POSITIVE', name='hitadjudicationstatus'), nullable=False),
    sa.Column('adjudicated_by_id', sa.Integer(), nullable=True),
    sa.Column('adjudication_rationale', sa.Text(), nullable=True),
    sa.Column('adjudicated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adjudicated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_id'], ['screening_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_hits_check_id'), 'screening_hits', ['check_id'], unique=False)
    op.create_index(op.f('ix_screening_hits_id'), 'screening_hits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_hits_id'), table_name='screening_hits')
    op.drop_index(op.f('ix_screening_hits_check_id'), table_name='screening_hits')
    op.drop_table('screening_hits')
    op.drop_index(op.f('ix_sar_records_internal_report_id'), table_name='sar_records')
    op.drop_index(op.f('ix_sar_records_id'), table_name='sar_records')
    op.drop_table('sar_records')
    op.drop_index(op.f('ix_screening_checks_matter_id'), table_name='screening_checks')
    op.drop_index(op.f('ix_screening_checks_id'), table_name='screening_checks')
    op.drop_table('screening_checks')
    op.drop_index(op.f('ix_kyb_checks_matter_id'), table_name='kyb_checks')
    op.drop_index(op.f('ix_kyb_checks_id'), table_name='kyb_checks')
    op.drop_index(op.f('ix_kyb_checks_company_number'), table_name='kyb_checks')
    op.drop_table('kyb_checks')
    op.drop_index(op.f('ix_internal_reports_reporter_id'), table_name='internal_reports')
    op.drop_index(op.f('ix_internal_reports_matter_id'), table_name='internal_reports')
    op.drop_index(op.f('ix_internal_reports_id'), table_name='internal_reports')
    op.drop_table('internal_reports')
    op.drop_index(op.f('ix_eidv_checks_provider_ref'), table_name='eidv_checks')
    op.drop_index(op.f('ix_eidv_checks_matter_id'), table_name='eidv_checks')
    op.drop_index(op.f('ix_eidv_checks_id'), table_name='eidv_checks')
    op.drop_table('eidv_checks')
    op.drop_index('ix_cmra_matter_type_status', table_name='client_matter_risk_assessments')
    op.drop_index(op.f('ix_client_matter_risk_assessments_status'), table_name='client_matter_risk_assessments')
    op.drop_index(op.f('ix_client_matter_risk_assessments_matter_id'), table_name='client_matter_risk_assessments')
    op.drop_index(op.f('ix_client_matter_risk_assessments_id'), table_name='client_matter_risk_assessments')
    op.drop_table('client_matter_risk_assessments')
    op.drop_index(op.f('ix_training_records_user_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_sanctions_entries_primary_name'), table_name='sanctions_entries')
    op.drop_index(op.f('ix_sanctions_entries_id'), table_name='sanctions_entries')
    op.drop_index(op.f('ix_sanctions_entries_external_id'), table_name='sanctions_entries')
    op.drop_index(op.f('ix_sanctions_entries_entity_type'), table_name='sanctions_entries')
    op.drop_index(op.f('ix_sanctions_entries_dataset_id'), table_name='sanctions_entries')
    op.drop_table('sanctions_entries')
    op.drop_index(op.f('ix_policy_documents_title'), table_name='policy_documents')
    op.drop_index(op.f('ix_policy_documents_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_firm_risk_assessments_version'), table_name='firm_risk_assessments')
    op.drop_index(op.f('ix_firm_risk_assessments_status'), table_name='firm_risk_assessments')
    op.drop_index(op.f('ix_firm_risk_assessments_id'), table_name='firm_risk_assessments')
    op.drop_table('firm_risk_assessments')
    op.drop_index(op.f('ix_sanctions_datasets_id'), table_name='sanctions_datasets')
    op.drop_table('sanctions_datasets')
    # ### end Alembic commands ###
