"""baseline: full schema 2026-07

Revision ID: 544067eefddd
Revises: 
Create Date: 2026-07-06 21:31:38.532798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544067eefddd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_country_risk',
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('prohibited', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('iso2')
    )
    op.create_table('transaction_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_config_key'), 'transaction_config', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PARTNER', 'ANALYST', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('matters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_entity_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUSINESS_PURCHASE', 'PROPERTY_PURCHASE', 'INVESTMENT', 'OTHER', name='transactiontype'), nullable=False),
    sa.Column('target_business_name', sa.String(length=255), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AWAITING_CLIENT', 'CLIENT_UPLOADING', 'UNDER_REVIEW', 'QUERIES_RAISED', 'APPROVED', 'REJECTED', 'COMPLETED', name='matterstatus'), nullable=False),
    sa.Column('risk_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskrating'), nullable=False),
    sa.Column('risk_rating_auto', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskrating'), nullable=True),
    sa.Column('risk_rating_override', sa.Boolean(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('risk_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_assessed_by', sa.String(length=200), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('compliance_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_submitted_by', sa.String(length=200), nullable=True),
    sa.Column('compliance_reason', sa.Text(), nullable=True),
    sa.Column('compliance_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('compliance_review_outcome', sa.String(length=20), nullable=True),
    sa.Column('compliance_review_notes', sa.Text(), nullable=True),
    sa.Column('assigned_analyst_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('portal_token', sa.String(length=500), nullable=True),
    sa.Column('portal_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('portal_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matters_client_name'), 'matters', ['client_name'], unique=False)
    op.create_index(op.f('ix_matters_id'), 'matters', ['id'], unique=False)
    op.create_index(op.f('ix_matters_portal_token'), 'matters', ['portal_token'], unique=True)
    op.create_index(op.f('ix_matters_reference_number'), 'matters', ['reference_number'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.Enum('RISK_RATING', 'SOF_ASSESSMENT', 'MATTER_COMPLETION', 'CHECK_WAIVER', name='approvaltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('assessment_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_storage_matter_id'), 'assessment_storage', ['matter_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'VIEWED', 'EXPORTED', 'APPROVED', 'REJECTED', 'UPLOADED', 'DOWNLOADED', 'STATUS_CHANGED', 'ASSIGNED', 'PORTAL_ACCESSED', 'MATTER_CREATED', 'REPORT_GENERATED', 'ALERT_REVIEWED', 'ARCHIVED', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', name='auditlogaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_matter_id'), 'audit_logs', ['matter_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('AMOUNT_CONSISTENCY', 'DATE_ALIGNMENT', 'IDENTITY_CONSISTENCY', 'SOURCE_LEGITIMACY', 'GAP_DETECTION', 'CIRCULAR_FLOW', 'UNEXPLAINED_CREDITS', 'MULTIPLE_SOURCES', 'TIMING_ANOMALY', 'CURRENCY_MISMATCH', name='checktype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='checkseverity'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'RESOLVED', 'WAIVED', 'ESCALATED', name='checkstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('affected_entities', sa.JSON(), nullable=True),
    sa.Column('affected_documents', sa.JSON(), nullable=True),
    sa.Column('affected_events', sa.JSON(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('variance', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_id'), 'checks', ['id'], unique=False)
    op.create_table('client_upload_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uploads', sa.Integer(), nullable=False),
    sa.Column('upload_count', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_upload_tokens_id'), 'client_upload_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_client_upload_tokens_matter_id'), 'client_upload_tokens', ['matter_id'], unique=False)
    op.create_index(op.f('ix_client_upload_tokens_token'), 'client_upload_tokens', ['token'], unique=True)
    op.create_table('document_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_category', sa.String(length=100), nullable=True),
    sa.Column('disk_filename', sa.String(length=500), nullable=True),
    sa.Column('file_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('VERIFIED', 'SUSPICIOUS', 'LIKELY_TAMPERED', 'PENDING', name='verificationverdict'), nullable=False),
    sa.Column('verification_phase', sa.String(length=30), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('metadata_result', sa.JSON(), nullable=True),
    sa.Column('structural_result', sa.JSON(), nullable=True),
    sa.Column('font_text_result', sa.JSON(), nullable=True),
    sa.Column('image_result', sa.JSON(), nullable=True),
    sa.Column('content_consistency_result', sa.JSON(), nullable=True),
    sa.Column('signature_result', sa.JSON(), nullable=True),
    sa.Column('annotation_form_result', sa.JSON(), nullable=True),
    sa.Column('hidden_content_result', sa.JSON(), nullable=True),
    sa.Column('file_integrity_result', sa.JSON(), nullable=True),
    sa.Column('template_match_result', sa.JSON(), nullable=True),
    sa.Column('extraction_result', sa.JSON(), nullable=True),
    sa.Column('math_check_result', sa.JSON(), nullable=True),
    sa.Column('anomaly_check_result', sa.JSON(), nullable=True),
    sa.Column('identified_bank_template', sa.String(length=200), nullable=True),
    sa.Column('bank_hint', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('account_identifier', sa.String(length=100), nullable=True),
    sa.Column('structural_pipeline_score', sa.Float(), nullable=True),
    sa.Column('statement_pipeline_score', sa.Float(), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=True),
    sa.Column('admin_override_by', sa.String(length=200), nullable=True),
    sa.Column('admin_override_rationale', sa.Text(), nullable=True),
    sa.Column('admin_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_proposed_by', sa.String(length=200), nullable=True),
    sa.Column('override_proposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_proposed_rationale', sa.Text(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_verifications_id'), 'document_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_document_verifications_matter_id'), 'document_verifications', ['matter_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.Enum('BANK_STATEMENT', 'COMPLETION_STATEMENT', 'SALE_PURCHASE_AGREEMENT', 'COMPANY_ACCOUNTS', 'TAX_RETURN', 'INVOICE', 'LOAN_AGREEMENT', 'PROBATE_LETTER', 'EXCHANGE_STATEMENT', 'PAYSLIP', 'DIVIDEND_VOUCHER', 'PROPERTY_DEED', 'GIFT_LETTER', 'ID_DOCUMENT', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('document_type_confidence', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_holder', sa.String(length=255), nullable=True),
    sa.Column('account_number_partial', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_issues', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('ocr_performed', sa.Boolean(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=True),
    sa.Column('user_corrections', sa.JSON(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('kyc_profiles',
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('expected_monthly_in', sa.Float(), nullable=True),
    sa.Column('expected_monthly_out', sa.Float(), nullable=True),
    sa.Column('nature_of_business', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_kyc_profiles_matter_id'), 'kyc_profiles', ['matter_id'], unique=False)
    op.create_table('matter_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_status_history_id'), 'matter_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_matter_status_history_matter_id'), 'matter_status_history', ['matter_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('BUSINESS_SALE', 'SAVINGS', 'DIVIDENDS', 'LOAN', 'INHERITANCE', 'GIFT', 'CRYPTO', 'PROPERTY_SALE', 'EMPLOYMENT', 'INVESTMENT_INCOME', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('date_received', sa.String(length=50), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('completeness_percentage', sa.Integer(), nullable=True),
    sa.Column('missing_items', sa.JSON(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('uploaded_document_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_id'), 'questionnaire_responses', ['id'], unique=False)
    op.create_table('statement_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('bank_hint', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('TRUSTED', 'REVIEW', 'HIGH_RISK', name='validationstatus'), nullable=False),
    sa.Column('identified_bank_template', sa.String(length=200), nullable=True),
    sa.Column('file_integrity_result', sa.JSON(), nullable=True),
    sa.Column('template_match_result', sa.JSON(), nullable=True),
    sa.Column('extraction_result', sa.JSON(), nullable=True),
    sa.Column('math_check_result', sa.JSON(), nullable=True),
    sa.Column('anomaly_check_result', sa.JSON(), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=True),
    sa.Column('admin_override_by', sa.String(length=200), nullable=True),
    sa.Column('admin_override_rationale', sa.Text(), nullable=True),
    sa.Column('admin_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_validations_id'), 'statement_validations', ['id'], unique=False)
    op.create_index(op.f('ix_statement_validations_matter_id'), 'statement_validations', ['matter_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('country_iso2', sa.String(length=2), nullable=True),
    sa.Column('payer_sort_code', sa.String(length=20), nullable=True),
    sa.Column('payee_sort_code', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_country_iso2'), 'transactions', ['country_iso2'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_matter_id'), 'transactions', ['matter_id'], unique=False)
    op.create_index(op.f('ix_transactions_txn_date'), 'transactions', ['txn_date'], unique=False)
    op.create_table('document_verification_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['document_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_verification_flags_id'), 'document_verification_flags', ['id'], unique=False)
    op.create_index(op.f('ix_document_verification_flags_verification_id'), 'document_verification_flags', ['verification_id'], unique=False)
    op.create_table('document_verification_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['document_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_verification_transactions_id'), 'document_verification_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_document_verification_transactions_verification_id'), 'document_verification_transactions', ['verification_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('PERSON', 'COMPANY', 'BANK_ACCOUNT', 'TRUST', 'PARTNERSHIP', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('account_number_partial', sa.String(length=50), nullable=True),
    sa.Column('sort_code', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('swift_bic', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('statement_validation_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='flagseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['validation_id'], ['statement_validations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_validation_flags_id'), 'statement_validation_flags', ['id'], unique=False)
    op.create_index(op.f('ix_statement_validation_flags_validation_id'), 'statement_validation_flags', ['validation_id'], unique=False)
    op.create_table('statement_validation_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['validation_id'], ['statement_validations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_validation_transactions_id'), 'statement_validation_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_statement_validation_transactions_validation_id'), 'statement_validation_transactions', ['validation_id'], unique=False)
    op.create_table('transaction_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('rule_tags', sa.JSON(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_outreach', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_alerts_created_at'), 'transaction_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_alerts_customer_id'), 'transaction_alerts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transaction_alerts_matter_id'), 'transaction_alerts', ['matter_id'], unique=False)
    op.create_index(op.f('ix_transaction_alerts_severity'), 'transaction_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_transaction_alerts_txn_id'), 'transaction_alerts', ['txn_id'], unique=False)
    op.create_table('fundsevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('SOURCE_GENERATION', 'TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'PAYMENT', 'FEE_DEDUCTION', 'CURRENCY_CONVERSION', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fees', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('converted_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('converted_currency', sa.String(length=3), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_entity_id', sa.Integer(), nullable=True),
    sa.Column('destination_entity_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('is_originating_event', sa.Boolean(), nullable=True),
    sa.Column('is_final_payment', sa.Boolean(), nullable=True),
    sa.Column('has_issues', sa.Boolean(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundsevents_id'), 'fundsevents', ['id'], unique=False)
    op.create_table('document_event_links',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('funds_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['funds_event_id'], ['fundsevents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'funds_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_event_links')
    op.drop_index(op.f('ix_fundsevents_id'), table_name='fundsevents')
    op.drop_table('fundsevents')
    op.drop_index(op.f('ix_transaction_alerts_txn_id'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_severity'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_matter_id'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_customer_id'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_created_at'), table_name='transaction_alerts')
    op.drop_table('transaction_alerts')
    op.drop_index(op.f('ix_statement_validation_transactions_validation_id'), table_name='statement_validation_transactions')
    op.drop_index(op.f('ix_statement_validation_transactions_id'), table_name='statement_validation_transactions')
    op.drop_table('statement_validation_transactions')
    op.drop_index(op.f('ix_statement_validation_flags_validation_id'), table_name='statement_validation_flags')
    op.drop_index(op.f('ix_statement_validation_flags_id'), table_name='statement_validation_flags')
    op.drop_table('statement_validation_flags')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_document_verification_transactions_verification_id'), table_name='document_verification_transactions')
    op.drop_index(op.f('ix_document_verification_transactions_id'), table_name='document_verification_transactions')
    op.drop_table('document_verification_transactions')
    op.drop_index(op.f('ix_document_verification_flags_verification_id'), table_name='document_verification_flags')
    op.drop_index(op.f('ix_document_verification_flags_id'), table_name='document_verification_flags')
    op.drop_table('document_verification_flags')
    op.drop_index(op.f('ix_transactions_txn_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_matter_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_country_iso2'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statement_validations_matter_id'), table_name='statement_validations')
    op.drop_index(op.f('ix_statement_validations_id'), table_name='statement_validations')
    op.drop_table('statement_validations')
    op.drop_index(op.f('ix_questionnaire_responses_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_matter_status_history_matter_id'), table_name='matter_status_history')
    op.drop_index(op.f('ix_matter_status_history_id'), table_name='matter_status_history')
    op.drop_table('matter_status_history')
    op.drop_index(op.f('ix_kyc_profiles_matter_id'), table_name='kyc_profiles')
    op.drop_table('kyc_profiles')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_verifications_matter_id'), table_name='document_verifications')
    op.drop_index(op.f('ix_document_verifications_id'), table_name='document_verifications')
    op.drop_table('document_verifications')
    op.drop_index(op.f('ix_client_upload_tokens_token'), table_name='client_upload_tokens')
    op.drop_index(op.f('ix_client_upload_tokens_matter_id'), table_name='client_upload_tokens')
    op.drop_index(op.f('ix_client_upload_tokens_id'), table_name='client_upload_tokens')
    op.drop_table('client_upload_tokens')
    op.drop_index(op.f('ix_checks_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_matter_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessment_storage_matter_id'), table_name='assessment_storage')
    op.drop_table('assessment_storage')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_matters_reference_number'), table_name='matters')
    op.drop_index(op.f('ix_matters_portal_token'), table_name='matters')
    op.drop_index(op.f('ix_matters_id'), table_name='matters')
    op.drop_index(op.f('ix_matters_client_name'), table_name='matters')
    op.drop_table('matters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_config_key'), table_name='transaction_config')
    op.drop_table('transaction_config')
    op.drop_table('ref_country_risk')
    # ### end Alembic commands ###
