/**
 * Shared plain-English translations for backend verification flag codes.
 * Used by SoFAssessment and the DocumentVerification components.
 */

export const FLAG_TRANSLATIONS: Record<string, { headline: string; explanation: string }> = {
  // Critical (PDF pipeline)
  PDF_OPEN_FAILED: {
    headline: 'Document could not be opened',
    explanation: 'The file is corrupted or is not a valid PDF document.',
  },
  ZERO_PAGES: {
    headline: 'Document is empty',
    explanation: 'The PDF file contains no pages. This is not a valid document.',
  },
  REDACT_ANNOTATIONS: {
    headline: 'Redaction marks found',
    explanation: 'This document contains redaction annotations used to hide original content. The underlying text may still be recoverable.',
  },
  TEXT_INPUT_FIELDS: {
    headline: 'Editable form fields detected',
    explanation: 'This document contains fillable text fields. Genuine bank statements are never editable — this strongly suggests the document was created from a blank template.',
  },
  FAKE_REDACTION: {
    headline: 'Content hidden behind black boxes',
    explanation: 'Black rectangles have been placed over text, but the original text is still readable underneath. This is a known tampering technique to conceal original figures.',
  },
  HIDDEN_LAYERS: {
    headline: 'Hidden content layers found',
    explanation: 'This document contains invisible layers that are switched off. These hidden layers may contain the original, unaltered content.',
  },
  WHITED_OUT_CONTENT: {
    headline: 'Content covered with white boxes',
    explanation: 'White rectangles have been placed over text to make it invisible, but the original text is still present underneath.',
  },
  // High (PDF pipeline)
  SUSPICIOUS_CREATOR: {
    headline: 'Created with image editing software',
    explanation: 'This document was created or modified using image editing or PDF manipulation software, rather than being generated by a bank.',
  },
  DATE_INCONSISTENCY: {
    headline: 'Document dates are contradictory',
    explanation: 'The modification date is earlier than the creation date, which is technically impossible. The document metadata has been tampered with.',
  },
  COPY_DISABLED: {
    headline: 'Text copying is blocked',
    explanation: 'This document prevents text from being selected or copied. This can be used to hide inconsistencies in altered documents.',
  },
  PRODUCER_DATE_MISMATCH: {
    headline: 'Software version doesn\'t match document date',
    explanation: 'The software listed as creating this document did not exist at the time the document claims to have been created.',
  },
  HAS_JAVASCRIPT: {
    headline: 'Embedded code detected',
    explanation: 'This document contains embedded computer code (JavaScript). Financial documents should never contain executable code.',
  },
  TEXT_OVER_IMAGE: {
    headline: 'Text layered over scanned images',
    explanation: 'Text has been placed on top of full-page scanned images. This is a common method of altering scanned bank statements by overlaying new text on the original scan.',
  },
  PAGE_INCONSISTENCY: {
    headline: 'Pages have different sizes',
    explanation: 'Some pages have different dimensions or rotation from the rest, suggesting pages may have been inserted from a different document.',
  },
  HEADER_INCONSISTENCY: {
    headline: 'Page headers do not match throughout',
    explanation: 'Some pages have different header or watermark text, suggesting pages may have been sourced from different documents.',
  },
  DPI_INCONSISTENCY: {
    headline: 'Images have inconsistent quality',
    explanation: 'The images in this document have very different resolutions, suggesting they were sourced from multiple documents or scanners.',
  },
  CONTENT_AFTER_CREATION: {
    headline: 'Content dates are after the file was created',
    explanation: 'The dates in the document text are significantly later than when the PDF itself was created. The document may have been backdated.',
  },
  FUTURE_DATES: {
    headline: 'Document contains future dates',
    explanation: 'This document references dates that have not yet occurred. This is a strong indicator that the content has been fabricated.',
  },
  FREETEXT_ANNOTATIONS: {
    headline: 'Text was added on top of the document',
    explanation: 'Text annotations were added on top of the original content after creation. This is a common method of altering figures in financial documents.',
  },
  HAS_FORM_FIELDS: {
    headline: 'Interactive form fields detected',
    explanation: 'This document contains interactive form fields. Genuine bank statements are static documents and should not contain any form elements.',
  },
  FORM_PDF_STRUCTURE: {
    headline: 'Built as a fillable form',
    explanation: 'The document has the internal structure of a fillable form. This is unusual for bank statements which are generated as fixed reports.',
  },
  HAS_LAYERS: {
    headline: 'Document contains multiple layers',
    explanation: 'This document has optional content layers, which are unusual in bank statements. Layers can be used to show or hide different versions of content.',
  },
  EXPECTED_SIGNATURE_MISSING: {
    headline: 'Expected bank digital signature is missing',
    explanation: 'This document appears to be from a bank that normally includes a digital signature on their statements, but no signature was found.',
  },
  // Medium (PDF pipeline)
  NO_METADATA: {
    headline: 'Document origin information removed',
    explanation: 'This document has no information about what software created it. Metadata is sometimes stripped to conceal the tools used to create or modify a document.',
  },
  LARGE_DATE_GAP: {
    headline: 'Modified long after creation',
    explanation: 'This document was modified a significant time after it was originally created, which can indicate later alterations.',
  },
  ENCRYPTED_PDF: {
    headline: 'Document is password-protected',
    explanation: 'This document is encrypted, which can restrict full analysis of its contents.',
  },
  MULTIPLE_EOF: {
    headline: 'Document has been re-saved multiple times',
    explanation: 'This document shows signs of having been saved multiple times after its initial creation. Each re-save can indicate edits were made.',
  },
  EMBEDDED_FILES: {
    headline: 'Hidden files found inside document',
    explanation: 'This document contains files embedded within it. This is unusual for bank statements.',
  },
  EXCESSIVE_FONTS: {
    headline: 'Unusually many fonts used',
    explanation: 'This document uses a large number of different fonts. Genuine bank statements typically use only 2\u20134 fonts. Multiple fonts can indicate content assembled from different sources.',
  },
  CROPPED_PAGES: {
    headline: 'Some pages have been cropped',
    explanation: 'Parts of some pages have been trimmed or hidden through cropping, which could be used to remove unwanted content.',
  },
  MIXED_COLOR_PROFILES: {
    headline: 'Images from different sources combined',
    explanation: 'This document contains images using different colour standards, suggesting they were sourced from different documents or devices.',
  },
  MIXED_DATE_FORMATS: {
    headline: 'Inconsistent date formatting',
    explanation: 'Multiple date formats are used. Genuine documents from a single source typically use a consistent format throughout.',
  },
  LOW_DPI_IMAGE: {
    headline: 'Very low quality image detected',
    explanation: 'An image in this document has very low resolution, possibly from a screenshot or poor-quality reproduction.',
  },
  ORPHANED_OBJECTS: {
    headline: 'Signs of heavy editing detected',
    explanation: 'This document contains leftover data fragments from previous edits, indicating it has been substantially modified.',
  },
  XREF_INTEGRITY: {
    headline: 'Internal structure has been altered',
    explanation: 'The document\u2019s internal cross-reference table shows anomalies consistent with direct manipulation of the file.',
  },
  HAS_ANNOTATIONS: {
    headline: 'Annotations found on document',
    explanation: 'This document contains annotations such as notes or highlights, which are unusual on official bank statements.',
  },
  // Statement / CSV pipeline
  BALANCE_ERRORS: {
    headline: 'Running balances do not add up',
    explanation: 'When adding each transaction to the previous balance, the numbers do not agree with the stated balances. Figures may have been altered.',
  },
  BALANCE_MINOR_ERRORS: {
    headline: 'Minor balance discrepancies found',
    explanation: 'Small rounding differences were found in the running balances. These are likely due to rounding but should be noted.',
  },
  SUM_CROSS_CHECK_FAIL: {
    headline: 'Transaction totals do not match',
    explanation: 'The sum of individual transactions does not match the stated totals. Transactions may have been added, removed, or altered.',
  },
  DATE_GAP_LARGE: {
    headline: 'Large gap in transaction dates',
    explanation: 'There is an unusually long period with no transactions. This may indicate missing pages or a partial statement.',
  },
  HIGH_DUPLICATE_RATE: {
    headline: 'Many duplicate transactions found',
    explanation: 'A high proportion of transactions appear to be identical. This is unusual and may indicate fabricated data.',
  },
  ROUND_NUMBER_BIAS: {
    headline: 'Unusual number of round-figure transactions',
    explanation: 'A disproportionate number of transactions are round figures, which can be an indicator of fabricated transaction data.',
  },
  UNIFORM_AMOUNTS: {
    headline: 'Transactions are suspiciously uniform',
    explanation: 'Many transactions have identical amounts, which is unusual for genuine bank account activity.',
  },
  NO_TEMPLATE_MATCH: {
    headline: 'Bank format not recognised',
    explanation: 'This statement does not match any known bank statement template. It may be from an unsupported bank or may not be genuine.',
  },
  HINT_MISMATCH: {
    headline: 'Statement does not match the specified bank',
    explanation: 'The content of this statement does not match the bank it was submitted as.',
  },
  NO_TRANSACTIONS: {
    headline: 'No transactions found',
    explanation: 'No transaction data could be extracted from this file. The file may be empty or in an unrecognised format.',
  },
  EXTRACTION_ERROR: {
    headline: 'Could not read statement data',
    explanation: 'An error occurred while trying to extract transaction data from this file.',
  },
  NO_DATA: {
    headline: 'No data available for checks',
    explanation: 'There is no transaction data to verify. The mathematical checks could not be performed.',
  },
  UNSUPPORTED_FORMAT: {
    headline: 'Statement format not supported',
    explanation: 'The file format or structure is not recognised as a valid bank statement.',
  },
  FILE_TOO_LARGE: {
    headline: 'File is unusually large',
    explanation: 'This file is significantly larger than expected for a bank statement.',
  },
  FILE_TOO_SMALL: {
    headline: 'File is too small to be valid',
    explanation: 'This file is too small to contain meaningful bank statement data.',
  },
  PERIOD_START_MISMATCH: {
    headline: 'Statement start date does not match',
    explanation: 'The earliest transaction does not align with the stated statement period start date.',
  },
  PERIOD_END_MISMATCH: {
    headline: 'Statement end date does not match',
    explanation: 'The latest transaction does not align with the stated statement period end date.',
  },

  // OCR consistency (Phase 1.1)
  TEXT_LAYER_OCR_MISMATCH: {
    headline: 'Visible text does not match the document text layer',
    explanation: 'The text shown on the page differs from the text encoded in the PDF. This is a classic indicator that someone has laid edited text over an image of the original document.',
  },
  OCR_CONSISTENCY_OK: {
    headline: 'OCR matches the document text layer',
    explanation: 'The visible text matches what is encoded in the PDF. No text-over-image tampering detected on the sampled pages.',
  },
  OCR_UNAVAILABLE: {
    headline: 'OCR check could not run',
    explanation: 'OCR libraries are not available in this environment; the text-over-image tamper check was skipped.',
  },

  // Cross-document corroboration (Phase 1.2)
  ACCOUNT_NAME_MISMATCH: {
    headline: 'Account holder name disagrees with other documents',
    explanation: 'The name on this document does not match the account holder name seen across other documents in this matter.',
  },
  ACCOUNT_NUMBER_MISMATCH: {
    headline: 'Account number disagrees with other documents',
    explanation: 'The account number/sort code on this document does not match the figures used on other documents in this matter.',
  },
  PERIOD_GAP_VS_OTHER_STATEMENTS: {
    headline: 'Statement period leaves a gap',
    explanation: 'The dates covered by this statement leave an unexplained gap relative to the other statements supplied for this matter.',
  },

  // Image forensics (Phase 3.10)
  IMAGE_ELA_ANOMALY: {
    headline: 'Embedded image shows signs of editing',
    explanation: 'Error-level analysis detected re-compression patterns consistent with image editing. Tampered patches typically reveal themselves as a localised brightness anomaly when the document is re-saved at a different JPEG quality.',
  },
  IMAGE_QUANT_TABLE_MIXED: {
    headline: 'Embedded images use different compression profiles',
    explanation: 'The JPEG quantisation tables across the embedded images are not all identical. Genuine bank statements are exported once with a single profile — mixed profiles are a strong indicator of image splicing.',
  },
  IMAGE_PHASH_RECORDED: {
    headline: 'Image fingerprints recorded',
    explanation: 'Perceptual hashes for the embedded images have been recorded for later cross-document lookup.',
  },
  IMAGE_FORENSICS_UNAVAILABLE: {
    headline: 'Image forensics not available',
    explanation: 'Image forensics libraries are not installed in this environment; the ELA/quant-table checks were skipped.',
  },
  IMAGE_FORENSICS_OPEN_FAILED: {
    headline: 'Image forensics could not open the document',
    explanation: 'The PDF could not be opened for image-level analysis. Other checks still ran.',
  },
  IMAGE_FORENSICS_ERROR: {
    headline: 'Image forensics ran into an error',
    explanation: 'The image-forensics stage raised an unexpected error and was skipped. Other checks still ran.',
  },

  // Template fingerprint (Phase 3.11)
  TEMPLATE_VISUAL_MISMATCH: {
    headline: 'Document does not match the registered template',
    explanation: 'This document claims to be from a known bank, but its visual layout does not match the registered template for that bank. This is a strong indicator that the document has been hand-built rather than issued by the bank.',
  },
  TEMPLATE_CHECK_ERROR: {
    headline: 'Template fingerprint check failed',
    explanation: 'The template-fingerprint stage raised an unexpected error and was skipped. Other checks still ran.',
  },

  // Digital signature validation (Phase 3.12)
  SIGNATURE_VALID: {
    headline: 'Digital signature is valid',
    explanation: 'The document carries a digital signature that has been validated. This is a strong positive indicator that the document has not been altered since signing.',
  },
  SIGNATURE_PRESENT_UNVERIFIED: {
    headline: 'Digital signature present but not verified',
    explanation: 'The document is digitally signed, but the certificate chain could not be verified in this environment. Treat as unverified.',
  },
  SIGNATURE_INVALID: {
    headline: 'Digital signature is invalid',
    explanation: 'The document has a digital signature that failed validation. Either the document has been modified after signing, or the signing certificate chain is broken/forged.',
  },
  SIGNATURE_ABSENT: {
    headline: 'No digital signature',
    explanation: 'The document has no digital signature. This is not by itself suspicious — many genuine documents are unsigned — but it provides no positive assurance.',
  },
  SIGNATURE_CHECK_ERROR: {
    headline: 'Signature validation ran into an error',
    explanation: 'The signature-validation stage raised an unexpected error and was skipped. Other checks still ran.',
  },
};

export const translateFlag = (flag: { code: string; message: string; severity: string }) => {
  const t = FLAG_TRANSLATIONS[flag.code];
  if (t) return t;
  return {
    headline: flag.message.length > 80 ? flag.message.substring(0, 77) + '...' : flag.message,
    explanation: flag.message,
  };
};
